"""Cross-language bias report: identical planted intent, divergent measurements.

For every language folder with a locked manifest, runs the same end-to-end scan the
verifier uses, then compares (a) per-signal corpus totals against the SPEC's planted
intent and (b) downstream per-file risk scores across languages. Because the planted
intent is identical everywhere, divergence IS measured language bias — either an
extraction inequality or a scoring inequality.

Usage:
    python tools/bias_report.py            # writes docs/bias_report.md
"""

import json
import pathlib
import sqlite3
import statistics
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import verify_language as vl

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "docs" / "bias_report.md"

# SPEC.md probe table: what every language plants, before any engine semantics.
PLANTED = {
    "branch": 3, "io": 3, "high_risk_execution": 2, "globals": 2, "test": 2,
    "safety": 2, "safety_bypasses": 2, "telemetry": 2, "state_mutation": 2,
    "cleanup": 2, "fragile_debt": 1, "planned_debt": 1, "import": 3,
    "func_start": 13, "args": 13, "class_start": 0, "doc": 1, "ownership": 1,
}

RISK_COLS = [
    "risk_cognitive_load", "risk_safety_score", "risk_tech_debt",
    "risk_api_exposure", "risk_dead_code",
]


def gather(language):
    language_dir = REPO_ROOT / "data" / language
    colmap = vl._signal_columns()
    with tempfile.TemporaryDirectory(prefix=f"rosetta_bias_{language}_") as tmp:
        db_path = vl.scan(language_dir, pathlib.Path(tmp))
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        have = {r[1] for r in conn.execute("PRAGMA table_info(file_data)")}
        sig_cols = [c for c in colmap if c in have]
        risk_cols = [c for c in RISK_COLS if c in have]
        rows = conn.execute(
            f"SELECT file_name, {', '.join(sig_cols + risk_cols)} FROM file_data"
        ).fetchall()
    totals = {colmap[c]: 0 for c in sig_cols}
    risks = {c: [] for c in risk_cols}
    for row in rows:
        for c in sig_cols:
            totals[colmap[c]] += row[c] or 0
        for c in risk_cols:
            if row[c] is not None:
                risks[c].append(row[c])
    return totals, {c: (statistics.mean(v) if v else None) for c, v in risks.items()}


def main():
    languages = sorted(
        p.parent.name for p in (REPO_ROOT / "data").glob("*/expected_signals.json")
    )
    if not languages:
        print("no locked manifests found")
        return 1

    ledger = json.loads((REPO_ROOT / "deviation_ledger.json").read_text())
    open_entries = [e["id"] for e in ledger["entries"] if e["status"] != "validated"]

    all_totals, all_risks = {}, {}
    for lang in languages:
        print(f"scanning {lang}...")
        all_totals[lang], all_risks[lang] = gather(lang)

    lines = [
        "# Cross-Language Bias Report",
        "",
        f"Generated by `tools/bias_report.py` over {len(languages)} locked language(s): "
        + ", ".join(languages) + ".",
        "",
        "Planted intent is identical in every language (SPEC.md probe table), so any "
        "column-to-column divergence below is measured language bias — an extraction "
        "inequality (signal table) or a scoring inequality (risk table). Every known "
        "deviation is validated in `deviation_ledger.json`; see per-language "
        "`expected_signals.json` notes for the shape-by-shape accounting.",
        "",
    ]
    if open_entries:
        lines += [f"**WARNING: unvalidated ledger entries present: {open_entries} — "
                  "treat this report as provisional (docs/GATING.md).**", ""]

    lines += ["## Signal totals vs. planted intent", "",
              "| signal | planted | " + " | ".join(languages) + " |",
              "|---|---|" + "---|" * len(languages)]
    divergent = []
    for sig, want in PLANTED.items():
        vals = [all_totals[lang].get(sig, 0) for lang in languages]
        mark = ""
        if len(set(vals)) > 1 or any(v != want for v in vals):
            mark = " ⚠"
            divergent.append(sig)
        lines.append(f"| {sig}{mark} | {want} | " + " | ".join(str(v) for v in vals) + " |")

    lines += ["", "## Mean per-file risk scores", "",
              "| risk | " + " | ".join(languages) + " |",
              "|---|" + "---|" * len(languages)]
    for col in RISK_COLS:
        vals = []
        for lang in languages:
            v = all_risks[lang].get(col)
            vals.append("—" if v is None else f"{v:.3f}")
        lines.append(f"| {col} | " + " | ".join(vals) + " |")

    lines += ["", f"**Signals diverging from uniform planted intent: "
              f"{len(divergent)}/{len(PLANTED)}** — {', '.join(divergent) if divergent else 'none'}.",
              "",
              "A risk-score spread on identical intent is the bottom-line bias number: "
              "same program, different measured risk, purely from language expression "
              "plus the ledgered engine behaviors.", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
