"""Per-language findings report: docs/findings_by_language.md.

Joins three sources the corpus already maintains:
  - deviation_ledger.json          (the defect, its disposition, the upstream issue)
  - data/<lang>/expected_signals.json  (file-level evidence: decoys + notes)
  - docs/bias_data.json            (scan cache written by bias_report.py: which
                                    metrics this language pushes into the red zone)

Runs standalone (reads the cache) or via bias_report.py, which calls generate()
after every scan so the report can never drift from the chart.
"""

import json
import pathlib
import re
import statistics
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "docs" / "findings_by_language.md"
CACHE = REPO_ROOT / "docs" / "bias_data.json"

GREEN_DEV = 0.25
AMBER_DEV = 0.50

_ISSUE = re.compile(r"squid-protocol/gitgalaxy#(\d+)")


def _issue_links(text):
    if not text:
        return "—"
    nums = _ISSUE.findall(text)
    if not nums:
        return "—"
    return " ".join(
        f"[#{n}](https://github.com/squid-protocol/gitgalaxy/issues/{n})" for n in nums
    )


def _first_sentence(text, limit=170):
    s = text.split(". ")[0].strip()
    return (s[: limit - 1] + "…") if len(s) > limit else s


def generate():
    if not CACHE.exists():
        print(f"missing {CACHE} — run tools/bias_report.py first")
        return 1
    cache = json.loads(CACHE.read_text())
    languages = cache["languages"]
    metrics = cache["metrics"]  # {metric: {lang: value}}
    ledger = json.loads((REPO_ROOT / "deviation_ledger.json").read_text())["entries"]

    manifests = {}
    for lang in languages:
        mp = REPO_ROOT / "data" / lang / "expected_signals.json"
        manifests[lang] = json.loads(mp.read_text()) if mp.exists() else {}

    # per-language red/amber zone membership
    zone = {lang: [] for lang in languages}
    for metric, values in metrics.items():
        vals = {l: v for l, v in values.items() if v is not None}
        if len(vals) < 2:
            continue
        med = statistics.median(vals.values())
        if med <= 0:
            continue
        for lang, v in vals.items():
            dev = (v - med) / med
            if abs(dev) > AMBER_DEV:
                zone[lang].append((metric, v, med, dev, "red"))
            elif abs(dev) > GREEN_DEV:
                zone[lang].append((metric, v, med, dev, "amber"))

    lines = [
        "# Findings by Language",
        "",
        "Generated by `tools/findings_report.py` (auto-refreshed by every "
        "`tools/bias_report.py` run). For each language: the metrics it pushes out of "
        "the acceptance band, every validated deviation shape that touches it, the "
        "upstream issue tracking each, and the corpus file carrying the evidence. "
        "Lifecycle rules: `docs/GATING.md`; full verdicts: `deviation_ledger.json`.",
        "",
        "## Index",
        "",
        "| language | red-zone metrics | amber | ledgered shapes | upstream issues |",
        "|---|---|---|---|---|",
    ]
    per_lang_shapes = {
        lang: [e for e in ledger
               if lang in e["languages_seen"] or e["languages_seen"] == ["all"]]
        for lang in languages
    }
    for lang in languages:
        reds = [z for z in zone[lang] if z[4] == "red"]
        ambers = [z for z in zone[lang] if z[4] == "amber"]
        shapes = per_lang_shapes[lang]
        issues = sorted({n for e in shapes for n in _ISSUE.findall(e.get("upstream_issue") or "")})
        lines.append(
            f"| [{lang}](#{lang}) | {len(reds)} | {len(ambers)} | {len(shapes)} | "
            + (" ".join(f"#{n}" for n in issues) if issues else "—") + " |"
        )

    for lang in languages:
        lines += ["", f"## {lang}", ""]
        reds = [z for z in zone[lang] if z[4] == "red"]
        ambers = [z for z in zone[lang] if z[4] == "amber"]
        if reds or ambers:
            lines += ["**Out-of-band metrics** (vs the cross-language median):", ""]
            for metric, v, med, dev, kind in sorted(reds) + sorted(ambers):
                flag = "🔴" if kind == "red" else "🟡"
                lines.append(f"- {flag} `{metric}`: {v:g} vs median {med:g} ({dev:+.0%})")
            lines.append("")
        else:
            lines += ["**In band on every metric.**", ""]

        shapes = per_lang_shapes[lang]
        if shapes:
            lines += [
                "| defect | type | issue | evidence in this folder | summary |",
                "|---|---|---|---|---|",
            ]
            decoys = manifests[lang].get("decoys", [])
            for e in sorted(shapes, key=lambda x: (x["disposition"], x["id"])):
                ev = [d["file"] for d in decoys
                      if e["id"] in (d.get("outcome") or "")]
                if not ev and e["id"] in (manifests[lang].get("notes") or ""):
                    ev = ["(notes)"]
                lines.append(
                    f"| `{e['id']}` | {e['disposition']} | "
                    f"{_issue_links(e.get('upstream_issue'))} | "
                    f"{', '.join(ev) if ev else '—'} | "
                    f"{_first_sentence(e['verdict'])} |"
                )
            lines.append("")

        if manifests[lang].get("decoys"):
            lines += ["<details><summary>Decoy outcomes (file-level evidence)</summary>", ""]
            for d in manifests[lang]["decoys"]:
                lines.append(f"- **{d['file']}** · `{d['line_hint']}` ({d['surface']}): {d['outcome']}")
            lines += ["", "</details>"]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(generate())
